source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'DemoApplication' do

  pod 'NIMKit', :path => '../'

  pod 'TMCache'
  
  pod 'JSONModel'
  
  pod 'SVGAPlayer'
  
  pod 'ReactiveObjC'
  
end
